### ISSUE TITLE
请问有办法实现，提供开放的api或者webhook之类的，来自动调用tmm刮削资源和重命名吗

### ISSUE THREAD

**Issue by latel** [dzhuang/tinymediamanager5-docker#3]
搜了下，tmm是有命令行接口的，https://www.tinymediamanager.org/docs/commandline
但是容器里没找到
```bash
find / -name tinyMediaManager
```

只找到个jar文件，用java执行报错
```bash
/tmp # java -jar /config/tmm.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/filter/Filter
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3076)
        at java.lang.Class.getMethod0(Class.java:3046)
        at java.lang.Class.getMethod(Class.java:1812)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.filter.Filter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
```

**Comment by dzhuang** [comment]
你要去tmm的gitlab上看看，https://gitlab.com/tinyMediaManager/tinyMediaManager

**Comment by dzhuang** [comment]
再看了你发的链接，可能的原因，那个是v4版的Docs，而image里是v5?

**Comment by longerpt** [comment]
> 再看了你发的链接，可能的原因，那个是v4版的Docs，而image里是v5?

请教一下V5的命令行是如何使用的呢？我参照v4的用法不行

**Comment by dzhuang** [comment]
Sorry, 我没有时间处理这个事项，我的建议是直接在gitlab问开发者，这肯定是最快最直接的
